### ISSUE TITLE
[readme] Readme's Chinese version is not chinese

### ISSUE THREAD

**Issue by ClSlaid** [al8n/stretto#15]
As is commented in the title.

**Comment by al8n** [comment]
Sorry, I have not translated the document to Chinese. I am busy with my work and my university study. Feel free to give a PR :).

**Comment by ClSlaid** [comment]
> Sorry, I have not translated the document to Chinese. I am busy with my work and my university study. Feel free to give a PR :).

Working on it, may I translate your project name into `余音` or something else? Or just stay as is in English.

**Comment by al8n** [comment]
It depends on your choice.

**Comment by ClSlaid** [comment]
> It depends on your choice.

Just commit a PR, but further proofreading and retouching are strongly needed.
