### ISSUE TITLE
[feature] Getting TTL value of entry

### ISSUE THREAD

**Issue by ClSlaid** [al8n/stretto#17]
proposing a new method that gets `ttl` value of an entry.

```rust
let val_ref = cache.get(&key).unwrap();
let ttl: std::time::Duration = val_ref.ttl();
let value = val_ref.value();
```

**Comment by al8n** [comment]
Hi @ClSlaid, I am busy in recent weeks, would you like to help implement this feature?

**Comment by ClSlaid** [comment]
> Hi @ClSlaid, I am busy in recent weeks, I may have a look this weekend if I have time, would you like to help implement this feature?

It's pretty hard, so many generics go bruhhhh...

I'll see what I can do...
