### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by bddap** [al8n/stretto#4]
Hey there, very cool library. I was looking it over and noticed a few miscellaneous things that might improve it. In no particular order:

There are a couple instances of sentinel values in the api.
- `Duration::ZERO` indicates infinite ttl. This isn't what I would expect. Consider using `Duration::MAX` instead. (should make implementation simpler too)
- When 0 is provided as an external cost, the provided `Coster` kicks in. This makes 0 a special value despite being a perfectly valid cost setting. Consider taking either an `Option` cost in setter methods, or using a separate setter method that doesn't take a cost parameter, and uses `Coster` to assign one.

It's advisable to make [invalid states unrepresentable](https://rust-lang.github.io/api-guidelines/dependability.html?search=#static-enforcement). Costs are expressed as `i64`, not `u64`. This struck me as odd. Are negative costs valid?

This [call to tokio select](https://github.com/al8n/stretto/blob/aa6b7012d0f897c321eb865b9075df5c4eb311d6/src/cache/axync.rs#L475) has only one future, which doesn't make sense considering what select does (it races multiple futures).

[Cargo clippy](https://github.com/rust-lang/rust-clippy) is a really handy tool for improving code. Among other things, it helps catch errors and keeps code idiomatic. I do recommend trying it out on this repo as can give really useful suggestions and teach you about rust idioms. It currently reports 49 suggestions for this codebase.

This last one might just be personal preference. Macros are immensely useful, but do have costs, like confusing rustfmt or sometimes confusing people trying to understand the code. That said, I see couple instances where use of custom macros can be reduced. [This](https://github.com/al8n/stretto/blob/e495db11a8dd1845bdfc170220736e7b26bc2344/src/cache/test.rs#L671) for example could be replaced with:
```rust
#[cfg(feature = "async")]
mod aync_test {
```

The consistent and idiomatic formatting is much appreciated by the way. Make it a lot easier to dive into the code.

Again I think this library is super cool and nicely written. If you'd like me to address any or all of these points via pr please let me know.

**Comment by bddap** [comment]
Oh, another suggestion: trait bounds on a struct definition can be, and usually are, un-ergonomic. [David Tolnay, creator of serde, explains why.](https://github.com/rust-lang/rust-clippy/issues/1689)

Take a look at [std::collections::HashMap](https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html) for an alternative. Hashmap doesn't impose bounds on its generic types in the struct definition. Instead the bounds are expressed on on an [impl block](https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html#impl-2). If `stretto::Cache<K, V, KH>` removed the bounds on `K` and `V` (and maybe `KH`) it would be easier use.

**Comment by al8n** [comment]
> Hey there, very cool library. I was looking it over and noticed a few miscellaneous things that might improve it. In no particular order:
> 
> There are a couple instances of sentinel values in the api.
> 
> * `Duration::ZERO` indicates infinite ttl. This isn't what I would expect. Consider using `Duration::MAX` instead. (should make implementation simpler too)
> * When 0 is provided as an external cost, the provided `Coster` kicks in. This makes 0 a special value despite being a perfectly valid cost setting. Consider taking either an `Option` cost in setter methods, or using a separate setter method that doesn't take a cost parameter, and uses `Coster` to assign one.
> 
> It's advisable to make [invalid states unrepresentable](https://rust-lang.github.io/api-guidelines/dependability.html?search=#static-enforcement). Costs are expressed as `i64`, not `u64`. This struck me as odd. Are negative costs valid?
> 
> This [call to tokio select](https://github.com/al8n/stretto/blob/aa6b7012d0f897c321eb865b9075df5c4eb311d6/src/cache/axync.rs#L475) has only one future, which doesn't make sense considering what select does (it races multiple futures).
> 
> [Cargo clippy](https://github.com/rust-lang/rust-clippy) is a really handy tool for improving code. Among other things, it helps catch errors and keeps code idiomatic. I do recommend trying it out on this repo as can give really useful suggestions and teach you about rust idioms. It currently reports 49 suggestions for this codebase.
> 
> This last one might just be personal preference. Macros are immensely useful, but do have costs, like confusing rustfmt or sometimes confusing people trying to understand the code. That said, I see couple instances where use of custom macros can be reduced. [This](https://github.com/al8n/stretto/blob/e495db11a8dd1845bdfc170220736e7b26bc2344/src/cache/test.rs#L671) for example could be replaced with:
> 
> ```rust
> #[cfg(feature = "async")]
> mod aync_test {
> ```
> 
> The consistent and idiomatic formatting is much appreciated by the way. Make it a lot easier to dive into the code.
> 
> Again I think this library is super cool and nicely written. If you'd like me to address any or all of these points via pr please let me know.

Hi, Thanks for your feedback, your feedbacks are really cool and helpful to improve the project. Feel free to make a PR for your ideas! The cost is `i64` because it is used for the SampledLFU.
